echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "I am learning branching in git and github"
echo "Proud of you batch-33"
echo "Our new batch will start on 4th Oct"
echo "I will be there in Hinjewadi office on sunday"
echo "our work is done"
echo "I am seen the work"
echo "Yesterday I think about it"